version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: app-postgres-docker
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_app
    volumes:
      # copy the sql script to create database
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
